# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compare_points <- function(x1, x2) {
    .Call('_DuelingOptimization_compare_points', PACKAGE = 'DuelingOptimization', x1, x2)
}

signRecovery <- function(x, y, delta) {
    .Call('_DuelingOptimization_signRecovery', PACKAGE = 'DuelingOptimization', x, y, delta)
}

f1_value <- function(x) {
    .Call('_DuelingOptimization_f1_value', PACKAGE = 'DuelingOptimization', x)
}

